
export default {
	FETCH_USER: 'FETCH_USER',
	FETCH_USER_REPOS: 'FETCH_USER_REPOS',
	FETCH_NEXT_USER: 'FETCH_NEXT_USER',
	FETCH_PREV_USER: 'FETCH_PREV_USER',

	// LIST action types
	ITEM_TOGGLE: 'ITEM_TOGGLE',
	UPDATE_REPOS: 'UPDATE_REPOS',
	FILTER_REPOS: 'FILTER_REPOS',
	ADD_REPO: 'ADD_REPO',
	DELETE_REPO: 'DELETE_REPO',
};
